version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - cd nodejs
      - npm ci
    finally:
      - cd ../
artifacts:
  files:
    - 'node_modules/**/*'
  base-directory: nodejs
  name: sdk
